site_name: template
site_description: TODO
site_author: Peinser
edit_uri: edit/main/docs/
repo_name: template
repo_url: TODO
copyright: Maintained by <a href="hello@peinser.com">Peinser</a>.

nav:
- Home:
  - Introduction: index.md
- Reference: reference/
plugins:
- search
- section-index
- literate-nav:
    nav_file: SUMMARY.md
- gen-files:
    scripts:
    - docs/gen_reference_pages.py
- mkdocstrings:
    watch:
    - src/template

theme:
  name: material
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - toc
  - toc.follow
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate

extra_css:
- stylesheets/extra.css

markdown_extensions:
- pymdownx.arithmatex:
    generic: true

extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false