name: Documentation
run-name: ${{ github.actor }} is building and deploying the documentation

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - docs/**
    - src/**
    - mkdocs.yml

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        python-version: "3.14"
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Deploy documentation
      run: |
        uv sync --group docs
        uv run mkdocs gh-deploy --clean --verbose
