name: Documentation
run-name: ${{ github.actor }} is building and deploying the documentation

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - docs/**
    - src/**
    - mkdocs.yml

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Setup Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.6.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Deploy documentation
      run: |
        git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/peinser/template.git
        git fetch
        poetry install --with docs
        poetry run mkdocs gh-deploy --clean --verbose