name: Documentation
run-name: ${{ github.actor }} is building and deploying the documentation

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - docs/**
    - src/**
    - mkdocs.yml

permissions:
  contents: write

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        python-version: "3.13"
    - name: Build documentation
      run: |
        uv sync --group docs --frozen
        uv run mkdocs build --verbose

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'site'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
