name: PyPI
run-name: ${{ github.actor }} is publishing a PyPI release

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - docker/**
    - src/**
    - tests/**
    - pyproject.yml

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Setup Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.6.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Publish
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_KEY }}
        poetry publish --build
